// Code generated by command: go run asm.go -out out/xctr_amd64.s -stubs out/stub_amd64.go -pkg hctr2. DO NOT EDIT.

//go:build gc && !purego

package hctr2

//go:noescape
func xctrAsm(nr int, xk *uint32, out *byte, in *byte, nblocks int, iv *[16]byte)
